CREATE TABLE [dbo].[Brands](
	[BrandID] [int] IDENTITY(1,1) NOT NULL,
	[BrandName] [nvarchar](50) NULL,
	CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED 
	(
		[BrandID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[CarImages](
	[CarImageID] [int] IDENTITY(1,1) NOT NULL,
	[CarID] [int] NOT NULL,
	[ImagePath] [nvarchar](50) NOT NULL,
	[ImageDate] [date] NOT NULL,
	CONSTRAINT [PK_CarImages] PRIMARY KEY CLUSTERED 
	(
		[CarImageID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Cars](
	[CarID] [int] IDENTITY(1,1) NOT NULL,
	[CarName] [nvarchar](50) NULL,
	[BrandID] [int] NOT NULL,
	[ModelYear] [int] NULL,
	[Description] [nvarchar](50) NULL,
	[ColorID] [int] NOT NULL,
	[DailyPrice] [decimal](18, 0) NULL,
	CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
	(
		[CarID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

CREATE TABLE [dbo].[Colors](
	[ColorID] [int] IDENTITY(1,1) NOT NULL,
	[ColorName] [nvarchar](50) NULL,
	CONSTRAINT [PK_Colors] PRIMARY KEY CLUSTERED 
	(
		[ColorID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[CompanyName] [nvarchar](50) NOT NULL,
	CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
	(
		[CustomerID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[OperationClaims](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
	CONSTRAINT [PK_OperationClaims] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Rentals](
	[RentalID] [int] IDENTITY(1,1) NOT NULL,
	[CarID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[RentDate] [date] NOT NULL,
	[ReturnDate] [date] NOT NULL,
	CONSTRAINT [PK_Rentals] PRIMARY KEY CLUSTERED 
	(
		[RentalID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


ALTER TABLE [dbo].[Cars]
ADD CONSTRAINT [FK_Cars_Brands] FOREIGN KEY ([BrandID]) REFERENCES [dbo].[Brands]([BrandID]);

ALTER TABLE [dbo].[Cars]
ADD CONSTRAINT [FK_Cars_Colors] FOREIGN KEY ([ColorID]) REFERENCES [dbo].[Colors]([ColorID]);


USE [master];
ALTER DATABASE [Rental] SET READ_WRITE;
